/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.smartcity.smart.lighting.system;

import Util.JwtUtil;
import grpc.generated.energy.*;
import grpc.generated.registry.*;
import grpc.generated.streetlight.*;
import grpc.generated.traffic.*;
import io.grpc.*;
import io.grpc.stub.*;
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.atomic.AtomicInteger;

/**
 *
 * @author darkp
 */
public class ClientGUIFrameForm extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ClientGUIFrameForm.class.getName());
    private ClientCallStreamObserver<?> clientStreamObserver;
        
    /**
     * Creates new form ClientGUIFrameForm
     */
    public ClientGUIFrameForm() {
        setTitle("Smart City Lighting System");
        initComponents();
        cancelBtn.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lightLocField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lightIDField = new javax.swing.JTextField();
        setBrightnessBtn = new javax.swing.JButton();
        getStatusBtn = new javax.swing.JButton();
        clientStreamBtn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        trafficLocField = new javax.swing.JTextField();
        getTrafficBtn = new javax.swing.JButton();
        serverStreamBtn = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        energyLocField = new javax.swing.JTextField();
        optimizeBtn = new javax.swing.JButton();
        bidiStreamBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        resultArea = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cancelBtn = new javax.swing.JButton();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setToolTipText("Smart City Lighting System");
        jPanel1.setName("Smart City Lighting System"); // NOI18N

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Street Light Control"));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Location:");
        jPanel2.add(jLabel2);

        lightLocField.setText("ZONE_A");
        jPanel2.add(lightLocField);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Light ID:");
        jPanel2.add(jLabel1);

        lightIDField.setText("LIGHT_1");
        jPanel2.add(lightIDField);

        setBrightnessBtn.setBackground(new java.awt.Color(204, 204, 204));
        setBrightnessBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        setBrightnessBtn.setText("Set Brightness");
        setBrightnessBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setBrightnessBtnActionPerformed(evt);
            }
        });
        jPanel2.add(setBrightnessBtn);

        getStatusBtn.setBackground(new java.awt.Color(204, 204, 204));
        getStatusBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        getStatusBtn.setText("Get Status");
        getStatusBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getStatusBtnActionPerformed(evt);
            }
        });
        jPanel2.add(getStatusBtn);

        clientStreamBtn.setBackground(new java.awt.Color(204, 204, 204));
        clientStreamBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        clientStreamBtn.setText("Adjust All Lights in Current Location");
        clientStreamBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientStreamBtnActionPerformed(evt);
            }
        });
        jPanel2.add(clientStreamBtn);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Traffic Detection"));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Location:");
        jPanel3.add(jLabel3);

        trafficLocField.setText("ZONE_A");
        jPanel3.add(trafficLocField);

        getTrafficBtn.setBackground(new java.awt.Color(204, 204, 204));
        getTrafficBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        getTrafficBtn.setText("Get Traffic Level");
        getTrafficBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getTrafficBtnActionPerformed(evt);
            }
        });
        jPanel3.add(getTrafficBtn);

        serverStreamBtn.setBackground(new java.awt.Color(204, 204, 204));
        serverStreamBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        serverStreamBtn.setText("Stream Traffic Updates");
        serverStreamBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serverStreamBtnActionPerformed(evt);
            }
        });
        jPanel3.add(serverStreamBtn);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Energy Optimization"));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Location:");
        jPanel5.add(jLabel4);

        energyLocField.setText("ZONE_A");
        jPanel5.add(energyLocField);

        optimizeBtn.setBackground(new java.awt.Color(204, 204, 204));
        optimizeBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        optimizeBtn.setText("Optimize Lighting");
        optimizeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optimizeBtnActionPerformed(evt);
            }
        });
        jPanel5.add(optimizeBtn);

        bidiStreamBtn.setBackground(new java.awt.Color(204, 204, 204));
        bidiStreamBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bidiStreamBtn.setText("Monitor Energy (BiDi Stream)");
        bidiStreamBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bidiStreamBtnActionPerformed(evt);
            }
        });
        jPanel5.add(bidiStreamBtn);

        resultArea.setColumns(20);
        resultArea.setRows(5);
        jScrollPane2.setViewportView(resultArea);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Output Display");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Smart City Lighting System");

        cancelBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cancelBtn.setForeground(new java.awt.Color(204, 0, 51));
        cancelBtn.setText("Cancel Stream");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(15, 15, 15)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(12, 12, 12)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cancelBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1);
        jPanel1.getAccessibleContext().setAccessibleName("Smart City Lighting System");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // ================= STREET =================

    private void setBrightnessBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setBrightnessBtnActionPerformed
        // TODO add your handling code here:
        String lightID = lightIDField.getText();
        String location = lightLocField.getText();
        try {
            if (location.isEmpty()) {
                throw new IllegalArgumentException("Location cannot be empty");
            }
            ManagedChannel registryChannel = ManagedChannelBuilder.forAddress("localhost", 50050).usePlaintext().build();
            RegistryServiceGrpc.RegistryServiceBlockingStub registryStub = RegistryServiceGrpc.newBlockingStub(registryChannel);

            ServiceResponse res = registryStub.getService(ServiceRequest.newBuilder().setServiceName("streetlight").build());
            String[] parts = res.getAddress().split(":");

            ManagedChannel channel = ManagedChannelBuilder.forAddress(parts[0], Integer.parseInt(parts[1])).usePlaintext().build();

            StreetLightControlServiceGrpc.StreetLightControlServiceBlockingStub stub
                    = attachJwt(StreetLightControlServiceGrpc.newBlockingStub(channel));

            SetBrightnessResponse response = stub.setBrightness(
                    SetBrightnessRequest.newBuilder()
                            .setLightID(lightID)
                            .setBrightnessLevel(70)
                            .build()
            );

            resultArea.append("[Unary] Set brightness for " + location + ", " + lightID + ": " + response.getStatus() + "\n");

        } catch (IllegalArgumentException e) {
            resultArea.append("Error setting brightness: INVALID_ARGUMENT: " + e.getMessage()+"\n");

        } catch (Exception ex) {
            resultArea.append("Error setting brightness: " + ex.getMessage() + "\n");
        }
    }//GEN-LAST:event_setBrightnessBtnActionPerformed

    private void getStatusBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getStatusBtnActionPerformed
        // TODO add your handling code here:
        String lightID = lightIDField.getText();
        String location = lightLocField.getText();
        try {
            if (location.isEmpty()) {
                throw new IllegalArgumentException("Location cannot be empty");
            }
            ManagedChannel registryChannel = ManagedChannelBuilder.forAddress("localhost", 50050).usePlaintext().build();
            RegistryServiceGrpc.RegistryServiceBlockingStub registryStub = RegistryServiceGrpc.newBlockingStub(registryChannel);

            ServiceResponse res = registryStub.getService(ServiceRequest.newBuilder().setServiceName("streetlight").build());
            String[] parts = res.getAddress().split(":");

            ManagedChannel channel = ManagedChannelBuilder.forAddress(parts[0], Integer.parseInt(parts[1])).usePlaintext().build();

            StreetLightControlServiceGrpc.StreetLightControlServiceBlockingStub stub
                    = attachJwt(StreetLightControlServiceGrpc.newBlockingStub(channel));

            GetLightStatusResponse status = stub.getLightStatus(
                    GetLightStatusRequest.newBuilder().setLightID(lightID).build()
            );

            resultArea.append("[Unary] Status for " + location + ", " + lightID + ": Brightness=" + status.getBrightnessLevel()
                    + ", Power=" + status.getPowerConsumption()
                    + ", Active=" + status.getIsActive() + "\n");

        } catch (IllegalArgumentException e) {
            resultArea.append("Error getting status: INVALID_ARGUMENT: " + e.getMessage()+"\n");
        } catch (Exception ex) {
            resultArea.append("Error getting status: " + ex.getMessage() + "\n");
        }
    }//GEN-LAST:event_getStatusBtnActionPerformed

    private void clientStreamBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientStreamBtnActionPerformed
        // TODO add your handling code here:
        String location = lightLocField.getText();
        try {
            if (location.isEmpty()) {
                throw new IllegalArgumentException("Location cannot be empty");
            }
            ManagedChannel registryChannel = ManagedChannelBuilder.forAddress("localhost", 50050).usePlaintext().build();
            RegistryServiceGrpc.RegistryServiceBlockingStub registryStub = RegistryServiceGrpc.newBlockingStub(registryChannel);

            ServiceResponse res = registryStub.getService(ServiceRequest.newBuilder().setServiceName("streetlight").build());
            String[] parts = res.getAddress().split(":");

            ManagedChannel channel = ManagedChannelBuilder.forAddress(parts[0], Integer.parseInt(parts[1])).usePlaintext().build();

            StreetLightControlServiceGrpc.StreetLightControlServiceStub stub
                    = attachJwt(StreetLightControlServiceGrpc.newStub(channel));

            CountDownLatch latch = new CountDownLatch(1);

            StreamObserver<SetBrightnessRequest> requestObserver = stub.adjustMultipleLights(
                    new StreamObserver<SetBrightnessResponse>() {
                public void onNext(SetBrightnessResponse value) {
                    resultArea.append("[Client Stream] \nAdjusting Lights in: " + location + " \n" + value.getMessage() + "\n");
                }

                public void onError(Throwable t) {
                    resultArea.append("Client stream error: " + t.getMessage() + "\n");
                    latch.countDown();
                }

                public void onCompleted() {
                    resultArea.append("Client streaming completed.\n");
                    latch.countDown();
                }
            });

            requestObserver.onNext(SetBrightnessRequest.newBuilder().setLightID("LIGHT_1").setBrightnessLevel((int) (Math.random() * 100)).build());
            requestObserver.onNext(SetBrightnessRequest.newBuilder().setLightID("LIGHT_2").setBrightnessLevel((int) (Math.random() * 100)).build());
            requestObserver.onNext(SetBrightnessRequest.newBuilder().setLightID("LIGHT_3").setBrightnessLevel((int) (Math.random() * 100)).build());
            requestObserver.onNext(SetBrightnessRequest.newBuilder().setLightID("LIGHT_4").setBrightnessLevel((int) (Math.random() * 100)).build());
            requestObserver.onNext(SetBrightnessRequest.newBuilder().setLightID("LIGHT_5").setBrightnessLevel((int) (Math.random() * 100)).build());
            requestObserver.onCompleted();

            latch.await();
            channel.shutdown();

        } catch (IllegalArgumentException e) {
            resultArea.append("Error in adjust multiple lights: INVALID_ARGUMENT: " + e.getMessage()+"\n");
        } catch (Exception ex) {
            resultArea.append("Error in adjust multiple lights: " + ex.getMessage() + "\n");
        }
    }//GEN-LAST:event_clientStreamBtnActionPerformed

    // ================= TRAFFIC =================

    private void getTrafficBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getTrafficBtnActionPerformed
        // TODO add your handling code here:
        String location = trafficLocField.getText();
        try {
            ManagedChannel registryChannel = ManagedChannelBuilder.forAddress("localhost", 50050).usePlaintext().build();
            RegistryServiceGrpc.RegistryServiceBlockingStub registryStub = RegistryServiceGrpc.newBlockingStub(registryChannel);

            ServiceResponse res = registryStub.getService(ServiceRequest.newBuilder().setServiceName("traffic").build());
            String[] parts = res.getAddress().split(":");

            ManagedChannel channel = ManagedChannelBuilder.forAddress(parts[0], Integer.parseInt(parts[1])).usePlaintext().build();

            TrafficDetectionServiceGrpc.TrafficDetectionServiceBlockingStub stub
                    = attachJwt(TrafficDetectionServiceGrpc.newBlockingStub(channel));

            TrafficResponse traffic = stub.getTrafficLevel(
                    TrafficRequest.newBuilder().setLocationID(location).build()
            );

            resultArea.append("[Unary] Traffic at " + location + ": Vehicles=" + traffic.getVehicleCount()
                    + ", Status=" + traffic.getTrafficStatus() + "\n");

        } catch (Exception ex) {
            resultArea.append("Error getting traffic: " + ex.getMessage() + "\n");
        }
    }//GEN-LAST:event_getTrafficBtnActionPerformed

    private void serverStreamBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serverStreamBtnActionPerformed
        // TODO add your handling code here:
        String location = trafficLocField.getText();
        try {
            if (location.isEmpty()) {
                throw new IllegalArgumentException("Location cannot be empty");
            }
            ManagedChannel registryChannel = ManagedChannelBuilder.forAddress("localhost", 50050).usePlaintext().build();
            RegistryServiceGrpc.RegistryServiceBlockingStub registryStub = RegistryServiceGrpc.newBlockingStub(registryChannel);

            ServiceResponse res = registryStub.getService(ServiceRequest.newBuilder().setServiceName("traffic").build());
            String[] parts = res.getAddress().split(":");

            ManagedChannel channel = ManagedChannelBuilder.forAddress(parts[0], Integer.parseInt(parts[1])).usePlaintext().build();

            TrafficDetectionServiceGrpc.TrafficDetectionServiceStub stub
                    = attachJwt(TrafficDetectionServiceGrpc.newStub(channel));

            CountDownLatch latch = new CountDownLatch(1);
            resultArea.append("[Server Stream] \n");
            AtomicInteger count = new AtomicInteger(1);
            
            ClientResponseObserver<TrafficRequest, TrafficResponse> responseObserver =
                new ClientResponseObserver<TrafficRequest, TrafficResponse>() {

            @Override
            public void beforeStart(ClientCallStreamObserver<TrafficRequest> requestStream) {
                cancelBtn.setEnabled(true);
                clientStreamObserver = requestStream; // (store for cancel)                
            }

            @Override
            public void onNext(TrafficResponse value) {
                    resultArea.append("Traffic at: " + location + ", Quarter-" + count.getAndIncrement() + ", Traffic: " + value.getTrafficStatus()
                            + ", Vehicles: " + value.getVehicleCount() + "\n");
                }
@Override
                public void onError(Throwable t) {
                    resultArea.append("Server stream error: " + t.getMessage() + "\n");
                    cancelBtn.setEnabled(false);
                    latch.countDown();
                }
@Override
                public void onCompleted() {
                    resultArea.append("Server streaming completed.\n");
                    cancelBtn.setEnabled(false);
                    latch.countDown();
                }
        };
            
            
            stub.streamTrafficUpdates(TrafficRequest.newBuilder().setLocationID(location).build(),
                    responseObserver
            );
            //latch.await();
            //channel.shutdown();

        } catch (IllegalArgumentException e) {
            resultArea.append("Error in stream traffic update: INVALID_ARGUMENT: " + e.getMessage()+"\n");
        } catch (Exception ex) {
            resultArea.append("Error in stream traffic update: " + ex.getMessage() + "\n");
        }
    }//GEN-LAST:event_serverStreamBtnActionPerformed

    // ================= ENERGY =================

    private void optimizeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optimizeBtnActionPerformed
        // TODO add your handling code here:
        String location = energyLocField.getText();
        try {
            ManagedChannel registryChannel = ManagedChannelBuilder.forAddress("localhost", 50050).usePlaintext().build();
            RegistryServiceGrpc.RegistryServiceBlockingStub registryStub = RegistryServiceGrpc.newBlockingStub(registryChannel);

            ServiceResponse res = registryStub.getService(ServiceRequest.newBuilder().setServiceName("energy").build());
            String[] parts = res.getAddress().split(":");

            ManagedChannel channel = ManagedChannelBuilder.forAddress(parts[0], Integer.parseInt(parts[1])).usePlaintext().build();

            EnergyOptimizationServiceGrpc.EnergyOptimizationServiceBlockingStub stub
                    = attachJwt(EnergyOptimizationServiceGrpc.newBlockingStub(channel));

            OptimizationResponse response = stub
                    .withDeadlineAfter(3, TimeUnit.SECONDS)
                    .optimizeLighting(
                            OptimizationRequest.newBuilder().setLocationID(location).build()
                    );

            resultArea.append("[Unary] Energy optimization for " + location + ": Brightness="
                    + response.getRecommendedBrightnessLevel()
                    + ", Estimated Saving=" + response.getEstimatedEnergySaving() + "\n");

            channel.shutdown();

        } catch (Exception ex) {
            resultArea.append("Error optimizing lighting: " + ex.getMessage() + "\n");
        }
    }//GEN-LAST:event_optimizeBtnActionPerformed

    private void bidiStreamBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bidiStreamBtnActionPerformed
        // TODO add your handling code here:
        String location = energyLocField.getText();
        try {
            if(location.isEmpty())
            {
                throw new IllegalArgumentException("Location cannot be empty");
            }
            ManagedChannel registryChannel = ManagedChannelBuilder.forAddress("localhost", 50050).usePlaintext().build();
            RegistryServiceGrpc.RegistryServiceBlockingStub registryStub = RegistryServiceGrpc.newBlockingStub(registryChannel);

            ServiceResponse res = registryStub.getService(ServiceRequest.newBuilder().setServiceName("energy").build());
            String[] parts = res.getAddress().split(":");

            ManagedChannel channel = ManagedChannelBuilder.forAddress(parts[0], Integer.parseInt(parts[1])).usePlaintext().build();

            EnergyOptimizationServiceGrpc.EnergyOptimizationServiceStub stub
                    = attachJwt(EnergyOptimizationServiceGrpc.newStub(channel));

            CountDownLatch latch = new CountDownLatch(1);

            resultArea.append("[BiDi Stream]\n");
            
            ClientResponseObserver<OptimizationRequest, OptimizationResponse> responseObserver =
                new ClientResponseObserver<OptimizationRequest, OptimizationResponse>() {

            @Override
            public void beforeStart(ClientCallStreamObserver<OptimizationRequest> requestStream) {
                cancelBtn.setEnabled(true);
                clientStreamObserver = requestStream; 
            }

            @Override
            public void onNext(OptimizationResponse value) {
                    resultArea.append("Energy Optimization for " + value.getLocationID()
                            + ", Traffic= " + value.getTrafficStatus()
                            + ", Brightness= " + value.getRecommendedBrightnessLevel()
                            + ", Estimated Saving= " + value.getEstimatedEnergySaving() + "\n");
                }              

                @Override
            public void onError(Throwable t) {
                    resultArea.append("BiDi streaming error: " + t.getMessage() + "\n");
                    cancelBtn.setEnabled(false);
                    latch.countDown();
                }

            @Override
            public void onCompleted() {
                    resultArea.append("BiDi streaming completed.\n");
                    cancelBtn.setEnabled(false);
                    latch.countDown();
                }
        };

            StreamObserver<OptimizationRequest> requestObserver = stub.monitorEnergy(responseObserver);

            requestObserver.onNext(OptimizationRequest.newBuilder().setLocationID("ZONE_A").build());
            requestObserver.onNext(OptimizationRequest.newBuilder().setLocationID("ZONE_B").build());
            requestObserver.onNext(OptimizationRequest.newBuilder().setLocationID("ZONE_C").build());
            requestObserver.onNext(OptimizationRequest.newBuilder().setLocationID("ZONE_D").build());
            requestObserver.onNext(OptimizationRequest.newBuilder().setLocationID("ZONE_E").build());
            requestObserver.onCompleted();

            //latch.await();
            //channel.shutdown();

        } catch (IllegalArgumentException e) {
            resultArea.append("Error in monitor energy bi-directional streaming: INVALID_ARGUMENT: " + e.getMessage()+"\n");
        } catch (Exception ex) {
            resultArea.append("Error in monitor energy bi-directional streaming: " + ex.getMessage() + "\n");
        }
    }//GEN-LAST:event_bidiStreamBtnActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        // TODO add your handling code here:
        try {
        if (clientStreamObserver != null) {
            clientStreamObserver.cancel("User cancelled", null); // ⭐ ADDED
            resultArea.append("Stream cancelled by user.\n");
            cancelBtn.setEnabled(false);
        } else {
            resultArea.append("No active stream.\n");
            cancelBtn.setEnabled(false);
        }
    } catch (Exception e) {
        resultArea.append("Cancel error: " + e.getMessage() + "\n");
    }
    }//GEN-LAST:event_cancelBtnActionPerformed

    // ================= JWT =================
    private <T extends AbstractStub<T>> T attachJwt(T stub) {
        String jwtToken = JwtUtil.generateToken("GUI-Client");

        Metadata metadata = new Metadata();
        Metadata.Key<String> authKey = Metadata.Key.of("auth-token", Metadata.ASCII_STRING_MARSHALLER);
        metadata.put(authKey, jwtToken);

        return MetadataUtils.attachHeaders(stub, metadata);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ClientGUIFrameForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bidiStreamBtn;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JButton clientStreamBtn;
    private javax.swing.JTextField energyLocField;
    private javax.swing.JButton getStatusBtn;
    private javax.swing.JButton getTrafficBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField lightIDField;
    private javax.swing.JTextField lightLocField;
    private javax.swing.JButton optimizeBtn;
    private javax.swing.JTextArea resultArea;
    private javax.swing.JButton serverStreamBtn;
    private javax.swing.JButton setBrightnessBtn;
    private javax.swing.JTextField trafficLocField;
    // End of variables declaration//GEN-END:variables
}
